version: '3.5'

services:
  frontproxy:
    container_name: frontproxy
    hostname: frontproxy
    image: nginx:1.20.1-alpine
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/private
    depends_on:
      - appstore-ui
      - appstore
    networks:
      - frontend
      - proxynet
  appstore-ui:
    container_name: appstore-ui
    hostname: appstore-ui
    image: registry.fit.fraunhofer.de/dataspace/appstore/idsappstoreuits/appstoreui-drm:latest
    restart: always
    expose:
      - 8082
    networks:
      - proxynet
  postgres:
    image: postgres
    container_name: appstore-postgres
    expose:
      - 5432
    env_file:
      - ./postgres.env
    networks:
      - proxynet
    volumes:
      - connector-data:/var/lib/postgresql/data
  appstore:
    container_name: appstore
    hostname: appstore
    image: registry.fit.fraunhofer.de/dataspace/appstore/idsappstorev6/appstore-drm:latest
    restart: always
    expose:
      - 8080
    env_file:
      - ./connector.env
    volumes:
      - search-data:/data/search:z
    networks:
      - proxynet
    depends_on:
      - postgres

networks:
  proxynet:
    name: reverseproxy_network
  frontend:
    name: frontend_network

volumes:
  connector-data: {}
  search-data: {}
